<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
<link href="<?php echo get_template_directory_uri(); ?>/_/css/lib/jquery.bxslider.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo get_template_directory_uri(); ?>/_/css/lib/jquery.isotope.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo get_template_directory_uri(); ?>/_/css/lib/jquery.magnific-popup.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo get_template_directory_uri(); ?>/_/css/lib/jquery.treeview.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo get_template_directory_uri(); ?>/style.dev.css" rel="stylesheet" type="text/css" />
