<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery-1.11.1.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.fitvids-1.1.0.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.bxslider.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.magnific-popup.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.treeview.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.isotope.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/jquery.unveil.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/froogaloop.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/libtech.main.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/components/libtech.shop.js"></script>
