<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/angular/angular.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/angular/angular-route.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/angular/angular-cookies.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/app.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/gender/gender.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/size/size.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/style/style.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/results/results.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/results/snowboard.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/results/snowboard-filters.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/apps/snowboard-finder/why/why.js"></script>
