<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/utils/Draggable.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/plugins/ThrowPropsPlugin.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/GSAP/TweenMax.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/libtech.snowboardbuilder.js"></script>
