<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/angular.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/angular-route.js"></script>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/libtech.snowboard-finder.js"></script>
