<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>
	<script type="text/javascript" src="<?php echo get_template_directory_uri(); ?>/_/js/lib/modernizr-2.7.2.js"></script>
